DROP DATABASE IF EXISTS BLOG_MVC;
CREATE DATABASE BLOG_MVC;

USE BLOG_MVC;

DROP TABLE if exists T_COMMENT;
DROP TABLE if exists T_POST;

-- t_USER Table structure
DROP TABLE IF EXISTS T_USER;

CREATE TABLE T_USER(
  USER_ID             INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  USER_FIRST_NAME     VARCHAR(50),
  USER_LAST_NAME      VARCHAR(50),
  USER_MAIL           VARCHAR(50),
  USER_PSEUDO         VARCHAR(50)  NOT NULL,
  USER_PASSWORD       VARCHAR(255) NOT NULL,
  USER_COUNTRY        VARCHAR(50),
  USER_IS_ADMIN       TINYINT(1),
  USER_ACTIVE         VARCHAR(255),
  USER_RESET_TOKEN    VARCHAR(255),
  USER_LAST_CONNEXION DATETIME,
  USER_LAST_ACTIVITY  DATETIME,
  USER_DATE_CREATION  DATETIME,
  USER_UPDATE_TS      TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  USER_IPADRESS       VARCHAR(50),
  PRIMARY KEY (USER_ID),
  UNIQUE KEY uk_MAIL   (USER_MAIL),
  UNIQUE KEY uk_PSEUDO (USER_PSEUDO)
) ENGINE=InnoDB CHARACTER SET utf8 COLLATE utf8_general_ci;

CREATE TABLE T_POST (
  POST_ID       INTEGER      PRIMARY KEY AUTO_INCREMENT,
  POST_DATE     DATETIME     NOT NULL,
  POST_TITLE    VARCHAR(100) NOT NULL,
  POST_CONTENT  VARCHAR(400) NOT NULL
) ENGINE=INNODB CHARACTER SET utf8 COLLATE utf8_general_ci;

CREATE TABLE T_COMMENT (
  COM_ID      INTEGER      PRIMARY KEY AUTO_INCREMENT,
  COM_DATE    DATETIME     NOT NULL,
  COM_AUTHOR  VARCHAR(100) NOT NULL,
  COM_CONTENT VARCHAR(200) NOT NULL,
  POST_ID     INTEGER      NOT NULL,
  constraint FK_COM_POST foreign key(POST_ID) references T_POST(POST_ID)
) ENGINE=INNODB CHARACTER SET utf8 COLLATE utf8_general_ci;

INSERT INTO T_POST(POST_DATE, POST_TITLE, POST_CONTENT) VALUES
(NOW(), 'First Post', 'Hello everyone! This is my first post on my blog.');
INSERT INTO T_POST(POST_DATE, POST_TITLE, POST_CONTENT) VALUES
(NOW(), 'Let\'s Work', 'We need to have content on this blog right now !');

INSERT INTO T_COMMENT(COM_DATE, COM_AUTHOR, COM_CONTENT, POST_ID) VALUES
(NOW(), 'Bob', 'Congrats for this beginning !!!', 1);
INSERT INTO T_COMMENT(COM_DATE, COM_AUTHOR, COM_CONTENT, POST_ID) VALUES
(NOW(), 'Me', 'Thank you, I\'m gonna to continue on this way', 1);

INSERT INTO T_USER(USER_PSEUDO, USER_PASSWORD) VALUES ('admin', 'secret');
